{
  validators {
    address
    voting_power
    proposer_priority
    details {
      operatorAddress
      tokens
      description {
        moniker
        identity
        profile_url
      }
      commission {
        rate
      }
    }
  }
}
